### ISSUE TITLE
permission usage error 

### ISSUE THREAD

**Issue by unix755** [unix755/xtools#7]
- https://go.dev/ref/spec#Integer_literals
use 0755, not 755
```go
// result: -rwxr-xr-x
fmt.Println(os.FileMode(0755))

// result: --wxrw--wx
fmt.Println(os.FileMode(755))
```

**Comment by gek64** [comment]
https://github.com/gek64/gek/commit/80e419514e611e72a216362c22d71ceb65a8ed6b
fixed
